/**
 * Persistence for the simulated pipeline clock and its generated output.
 *
 * Responsibilities:
 *  - Read / advance `pipeline_state.simulated_today` (single-row table).
 *  - Purge the [OUTPUT] rows of a specific as_of_date so a retry can rebuild
 *    them cleanly before the ML sidecar re-runs the chain.
 *
 * IMPORTANT: only the backend mutates `pipeline_state`. The ML sidecar reads
 * the simulated date (or an explicit override) and writes only the [OUTPUT]
 * tables directly.
 */
import { query } from '../../config/database.js';
import { logger } from '../../config/logger.js';
import { ApiError } from '../../shared/errors/api-errors.js';

/** Every table regenerated by the daily rollover, keyed by as_of_date. */
const OUTPUT_TABLES = [
  'forecasts_final',
  'replenishment_orders',
  'transfer_plan',
  'writeoff_risk',
  'simulation_daily',
  'kpi_summary',
  'alerts',
  'alert_digest',
  'rolling_run_log',
] as const;

export interface PipelineState {
  simulatedToday: string;
}

export class PipelineStateRepository {
  private async getStateRow(): Promise<string> {
    const stateRow = await query<{ simulated_today: string }>(
      'SELECT simulated_today::text FROM pipeline_state WHERE id = 1',
    );
    const simulatedToday = stateRow.rows[0]?.simulated_today;
    if (!simulatedToday) {
      throw ApiError.serviceUnavailable(
        'pipeline_state table is empty — run seed_staging.py first',
      );
    }
    return simulatedToday;
  }

  /** Current simulated date (yyyy-MM-dd). */
  async getSimulatedToday(): Promise<string> {
    return this.getStateRow();
  }

  /** Advance the simulated clock by N days and return the new date. */
  async advanceDays(days: number): Promise<{ from: string; to: string }> {
    const from = await this.getStateRow();

    const result = await query<{ new_date: string }>(
      `UPDATE pipeline_state
       SET simulated_today = simulated_today + make_interval(days => $1),
           updated_at = CURRENT_TIMESTAMP
       WHERE id = 1
       RETURNING simulated_today::text AS new_date`,
      [days],
    );
    const to = result.rows[0]?.new_date;
    if (!to) {
      throw ApiError.serviceUnavailable('pipeline_state update returned no row');
    }
    return { from, to };
  }

  /**
   * Delete all generated [OUTPUT] rows belonging to a given as_of_date.
   * Used before a retry so the rebuilt chain starts from a clean slate.
   * Returns a map of table -> rows deleted.
   */
  async purgeOutputForDate(asOf: string): Promise<Record<string, number>> {
    const purged: Record<string, number> = {};
    for (const table of OUTPUT_TABLES) {
      const result = await query(`DELETE FROM ${table} WHERE as_of_date = $1`, [
        asOf,
      ]);
      purged[table] = result.rowCount ?? 0;
    }
    logger.info(
      { asOf, purged },
      'Purged pipeline output for retry before re-execution',
    );
    return purged;
  }
}
