-- =============================================================
-- PHARMA SUPPLY CHAIN ML SYSTEM — POSTGRESQL SCHEMA
-- =============================================================
-- Category Legend:
--   [INPUT]          Static master data, written once
--   [INPUT-ROLLING]  Grows daily with new data
--   [DERIVED]        Computed from demand_history periodically
--   [OUTPUT]         Generated by ML pipeline each daily run
-- =============================================================

-- (removed) CREATE DATABASE statement — create the database separately in PostgreSQL, e.g.:
-- CREATE DATABASE pharma_sc;

-- (removed) USE statement — connect to the database via \c pharma_sc in psql instead

-- =============================================================
-- [INPUT] 1. sku_master
-- Core product master. No category_share here (see sku_market_share_monthly).
-- =============================================================
CREATE TABLE sku_master (
    id                        BIGINT        GENERATED ALWAYS AS IDENTITY,
    sku_id                    VARCHAR(20)   NOT NULL,
    brand_name                VARCHAR(100)  NOT NULL,
    atc_code                  VARCHAR(10)   NOT NULL,
    manufacturer              VARCHAR(100)  NOT NULL,
    regulatory_class          VARCHAR(30)   NOT NULL,
    hsn_code                  VARCHAR(20),
    nlem_listed               BOOLEAN       NOT NULL DEFAULT FALSE,
    criticality               VARCHAR(20)   NOT NULL,
    criticality_rationale     VARCHAR(300),
    criticality_reviewed_on   DATE,
    criticality_reviewed_by   VARCHAR(100),
    unit_cost_inr             INT           NOT NULL,
    shelf_life_days           INT           NOT NULL,
    created_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_sku_id UNIQUE (sku_id)
);


-- =============================================================
-- [INPUT] 2. locations
-- Warehouse / DC master. No demand_share here (see location_demand_summary).
-- =============================================================
CREATE TABLE locations (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    location_id     VARCHAR(30)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    type            VARCHAR(30)  NOT NULL,
    capacity_units  INT          NOT NULL DEFAULT 0,
    city            VARCHAR(80),
    state           VARCHAR(80),
    pincode         VARCHAR(10),
    gstin           VARCHAR(20),
    commissioned_on DATE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_location_id UNIQUE (location_id)
);


-- =============================================================
-- [INPUT] 3. lanes
-- Supply lanes: SUPPLIER→location (replenish) or DC→WH (transfer)
-- =============================================================
CREATE TABLE lanes (
    id              BIGINT      GENERATED ALWAYS AS IDENTITY,
    from_location   VARCHAR(30) NOT NULL,
    to_location     VARCHAR(30) NOT NULL,
    mode            VARCHAR(20) NOT NULL,
    lead_time_days  INT         NOT NULL,
    carrier         VARCHAR(100),
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_lane UNIQUE (from_location, to_location, mode)
);


-- =============================================================
-- [INPUT] 4. distributors
-- One distributor per location/region.
-- =============================================================
CREATE TABLE distributors (
    id                  BIGINT      GENERATED ALWAYS AS IDENTITY,
    distributor_id      VARCHAR(30) NOT NULL,
    region              VARCHAR(30) NOT NULL,
    distributor_name    VARCHAR(150),
    order_cycle_days    INT         NOT NULL,
    order_size_sigma    DECIMAL(5,3) NOT NULL,
    contact_email       VARCHAR(150),
    created_at          TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_distributor_id UNIQUE (distributor_id)
);


-- =============================================================
-- [INPUT] 5. promo_calendar
-- Marketing promotions. Past promos show actual vs planned uplift.
-- =============================================================
CREATE TABLE promo_calendar (
    id                  BIGINT       GENERATED ALWAYS AS IDENTITY,
    promo_id            VARCHAR(30)  NOT NULL,
    name                VARCHAR(100) NOT NULL,
    start_date          DATE         NOT NULL,
    end_date            DATE         NOT NULL,
    planned_uplift_pct  DECIMAL(5,3) NOT NULL,
    actual_uplift_pct   DECIMAL(5,3),
    regions             TEXT         NOT NULL,
    target_atc_codes    VARCHAR(200),
    status              VARCHAR(20)  NOT NULL DEFAULT 'planned',
    created_by          VARCHAR(100),
    approved_on         DATE,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [INPUT-ROLLING] 6. demand_history
-- Daily sales per SKU per region. Core ML training input. Grows daily.
-- =============================================================
CREATE TABLE demand_history (
    id          BIGINT      GENERATED ALWAYS AS IDENTITY,
    date        DATE        NOT NULL,
    sku_id      VARCHAR(20) NOT NULL,
    atc_code    VARCHAR(10) NOT NULL,
    region      VARCHAR(30) NOT NULL,
    units       INT         NOT NULL DEFAULT 0,
    ingested_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_demand UNIQUE (date, sku_id, region)
);


-- =============================================================
-- [INPUT-ROLLING] 7. disease_burden_index
-- Daily ILI/flu burden per region. Sourced from public health APIs.
-- (Previously flu_index — renamed and enriched with source metadata)
-- =============================================================
CREATE TABLE disease_burden_index (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    record_date     DATE         NOT NULL,
    region          VARCHAR(30)  NOT NULL,
    index_value     DECIMAL(8,2) NOT NULL,
    index_type      VARCHAR(30)  NOT NULL DEFAULT 'ili',
    source          VARCHAR(100) NOT NULL DEFAULT 'IDSP_State_Surveillance',
    source_lag_days SMALLINT      NOT NULL DEFAULT 3,
    ingested_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_dbi UNIQUE (record_date, region)
);


-- =============================================================
-- [INPUT-ROLLING] 8. inventory_batches
-- On-hand inventory snapshot per batch. New snapshot rows each day.
-- Use as_of_date to filter to latest state.
-- =============================================================
CREATE TABLE inventory_batches (
    id              BIGINT      GENERATED ALWAYS AS IDENTITY,
    as_of_date      DATE        NOT NULL,
    batch_id        VARCHAR(20) NOT NULL,
    sku_id          VARCHAR(20) NOT NULL,
    location        VARCHAR(30) NOT NULL,
    qty_units       INT         NOT NULL DEFAULT 0,
    expiry_date     DATE        NOT NULL,
    received_date   DATE        NOT NULL,
    unit_cost_inr   INT         NOT NULL,
    status          VARCHAR(30) NOT NULL,
    grn_number      VARCHAR(50),
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [INPUT-ROLLING] 9. distributor_orders
-- Actual historical orders placed by each distributor over time.
-- Captures real ordering patterns: cycle compliance, order size variance,
-- partial fulfillments. This is what "distributor order patterns" means.
-- Populated by: daily ingest of distributor PO data.
-- =============================================================
CREATE TABLE distributor_orders (
    id                    BIGINT        GENERATED ALWAYS AS IDENTITY,
    order_id              VARCHAR(40)   NOT NULL,
    distributor_id        VARCHAR(30)   NOT NULL,
    region                VARCHAR(30)   NOT NULL,
    sku_id                VARCHAR(20)   NOT NULL,
    atc_code              VARCHAR(10)   NOT NULL,
    order_date            DATE          NOT NULL,
    expected_delivery     DATE,
    actual_delivery       DATE,
    ordered_qty           INT           NOT NULL,
    fulfilled_qty         INT           NOT NULL DEFAULT 0,
    unit_cost_inr         INT           NOT NULL,
    order_value_inr       INT           NOT NULL,
    days_since_last_order INT,
    fulfillment_status    VARCHAR(20)   NOT NULL DEFAULT 'pending',
    shortfall_qty         INT           NOT NULL DEFAULT 0,
    ingested_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_order UNIQUE (order_id, sku_id)
);


-- =============================================================
-- [INPUT-ROLLING] 10. warehouse_capacity_log
-- Weekly snapshot of warehouse capacity utilization per location.
-- The static capacity_units in locations table shows max capacity.
-- This table shows how utilization changed over time — vital for
-- "Warehouse Capacity" dashboard charts and capacity planning.
-- Populated by: weekly aggregation from inventory_batches.
-- =============================================================
CREATE TABLE warehouse_capacity_log (
    id               BIGINT        GENERATED ALWAYS AS IDENTITY,
    snapshot_date    DATE          NOT NULL,
    location_id      VARCHAR(30)   NOT NULL,
    capacity_units   INT           NOT NULL,
    used_units       INT           NOT NULL,
    available_units  INT           NOT NULL,
    utilization_pct  DECIMAL(5,2)  NOT NULL,
    near_expiry_units INT          NOT NULL DEFAULT 0,
    sku_count        INT           NOT NULL DEFAULT 0,
    computed_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_capacity UNIQUE (snapshot_date, location_id)
);


-- =============================================================
-- [DERIVED] 11. sku_market_share_monthly
-- Brand share within ATC category, computed monthly from demand_history.
-- Replaces the static category_share field that was in sku_master.
-- =============================================================
CREATE TABLE sku_market_share_monthly (
    id                  BIGINT       GENERATED ALWAYS AS IDENTITY,
    sku_id              VARCHAR(20)  NOT NULL,
    atc_code            VARCHAR(10)  NOT NULL,
    period_year         SMALLINT     NOT NULL,
    period_month        SMALLINT      NOT NULL,
    total_units_sold    INT          NOT NULL,
    category_units_sold INT          NOT NULL,
    market_share        DECIMAL(6,4) NOT NULL,
    computed_on         DATE         NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_sku_period UNIQUE (sku_id, period_year, period_month)
);


-- =============================================================
-- [DERIVED] 12. location_demand_summary
-- Quarterly regional demand contribution computed from demand_history.
-- Replaces the static demand_share field that was in locations.
-- =============================================================
CREATE TABLE location_demand_summary (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    location_id     VARCHAR(30)  NOT NULL,
    period_year     SMALLINT     NOT NULL,
    period_quarter  SMALLINT      NOT NULL,
    total_units     INT          NOT NULL,
    national_share  DECIMAL(6,4) NOT NULL,
    yoy_growth_pct  DECIMAL(7,2),
    computed_on     DATE         NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_loc_period UNIQUE (location_id, period_year, period_quarter)
);


-- =============================================================
-- [DERIVED] 13. sku_cost_history
-- Full cost timeline per SKU. Real costs change every 1–2 years.
-- =============================================================
CREATE TABLE sku_cost_history (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    sku_id          VARCHAR(20)  NOT NULL,
    unit_cost_inr   INT          NOT NULL,
    effective_from  DATE         NOT NULL,
    effective_to    DATE,
    reason          VARCHAR(200),
    approved_by     VARCHAR(100),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [OUTPUT] 14. forecasts_final
-- ML ensemble forecast per SKU, region, horizon. One batch per daily run.
-- =============================================================
CREATE TABLE forecasts_final (
    id               BIGINT        GENERATED ALWAYS AS IDENTITY,
    as_of_date       DATE          NOT NULL,
    sku_id           VARCHAR(20)   NOT NULL,
    atc_code         VARCHAR(10)   NOT NULL,
    region           VARCHAR(30)   NOT NULL,
    forecast_date    DATE          NOT NULL,
    horizon          INT           NOT NULL,
    p10              DECIMAL(12,2) NOT NULL,
    p50              DECIMAL(12,2) NOT NULL,
    p90              DECIMAL(12,2) NOT NULL,
    momentum_u       DECIMAL(10,4),
    flu_ratio        DECIMAL(8,4),
    sense_adjustment DECIMAL(8,4),
    models_used      VARCHAR(100),
    lgbm_weight      DECIMAL(5,3),
    chronos_weight   DECIMAL(5,3),
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_forecast UNIQUE (as_of_date, sku_id, region, forecast_date)
);


-- =============================================================
-- [OUTPUT] 15. replenishment_orders
-- Computed reorder plan per SKU per region. Generated by replenishment.py.
-- =============================================================
CREATE TABLE replenishment_orders (
    id                     BIGINT        GENERATED ALWAYS AS IDENTITY,
    as_of_date             DATE          NOT NULL,
    sku_id                 VARCHAR(20)   NOT NULL,
    region                 VARCHAR(30)   NOT NULL,
    criticality            VARCHAR(20)   NOT NULL,
    lead_time_days         INT           NOT NULL,
    service_level          DECIMAL(4,2)  NOT NULL,
    mu_daily               DECIMAL(10,2) NOT NULL,
    sigma_daily            DECIMAL(10,2) NOT NULL,
    safety_stock           INT           NOT NULL,
    target_position        INT           NOT NULL,
    on_hand                INT           NOT NULL,
    order_qty              INT           NOT NULL,
    order_value_inr        INT           NOT NULL,
    days_of_supply_on_hand DECIMAL(8,2),
    status                 VARCHAR(30)   NOT NULL,
    created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_repl UNIQUE (as_of_date, sku_id, region)
);


-- =============================================================
-- [OUTPUT] 16. transfer_plan
-- Intra-network transfer recommendations. Generated by allocation.py.
-- =============================================================
CREATE TABLE transfer_plan (
    id                        BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date                DATE         NOT NULL,
    batch_id                  VARCHAR(20),
    sku_id                    VARCHAR(20)  NOT NULL,
    from_location             VARCHAR(30)  NOT NULL,
    to_location               VARCHAR(30)  NOT NULL,
    qty_units                 INT          NOT NULL,
    expiry_date               DATE,
    days_to_expiry            INT,
    transfer_lead_days        INT          NOT NULL,
    value_saved_inr           INT          NOT NULL DEFAULT 0,
    reason                    VARCHAR(30)  NOT NULL,
    src_days_of_supply_before DECIMAL(8,2),
    created_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [OUTPUT] 17. writeoff_risk
-- Batches at risk of write-off after transfer plan applied. Generated by allocation.py.
-- =============================================================
CREATE TABLE writeoff_risk (
    id                      BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date              DATE         NOT NULL,
    batch_id                VARCHAR(20)  NOT NULL,
    sku_id                  VARCHAR(20)  NOT NULL,
    location                VARCHAR(30)  NOT NULL,
    qty_units               INT          NOT NULL,
    leftover                INT          NOT NULL,
    residual_writeoff_units INT          NOT NULL,
    unit_cost_inr           INT          NOT NULL,
    residual_value_inr      INT          NOT NULL,
    expiry_date             DATE         NOT NULL,
    days_to_expiry          INT          NOT NULL,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [OUTPUT] 18. simulation_daily
-- Day-by-day simulation log for proposed vs status_quo policy.
-- Generated by simulate.py. Large table — index carefully.
-- =============================================================
CREATE TABLE simulation_daily (
    id                  BIGINT        GENERATED ALWAYS AS IDENTITY,
    as_of_date          DATE          NOT NULL,
    policy              VARCHAR(20)   NOT NULL,
    date                DATE          NOT NULL,
    sku_id              VARCHAR(20)   NOT NULL,
    region              VARCHAR(30)   NOT NULL,
    criticality         VARCHAR(20)   NOT NULL,
    demand              DECIMAL(12,2) NOT NULL,
    fulfilled           DECIMAL(12,2) NOT NULL,
    unfulfilled         DECIMAL(12,2) NOT NULL DEFAULT 0,
    expired_units       DECIMAL(12,2) NOT NULL DEFAULT 0,
    expired_value_inr   DECIMAL(14,2) NOT NULL DEFAULT 0,
    ending_inventory    DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [OUTPUT] 19. kpi_summary
-- High-level KPIs per policy per run. Generated by simulate.py.
-- =============================================================
CREATE TABLE kpi_summary (
    id                           BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date                   DATE         NOT NULL,
    policy                       VARCHAR(20)  NOT NULL,
    fill_rate_pct                DECIMAL(6,2) NOT NULL,
    critical_fill_rate_pct       DECIMAL(6,2) NOT NULL,
    stockout_units               INT          NOT NULL DEFAULT 0,
    critical_stockout_sitedays   INT          NOT NULL DEFAULT 0,
    writeoff_value_inr           BIGINT       NOT NULL DEFAULT 0,
    avg_ending_inventory         DECIMAL(14,2),
    created_at                   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_kpi UNIQUE (as_of_date, policy)
);


-- =============================================================
-- [OUTPUT] 20. alerts
-- Machine-generated supply chain alerts. Generated by alerts.py.
-- is_acknowledged allows frontend to track user actions.
-- =============================================================
CREATE TABLE alerts (
    id                BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date        DATE         NOT NULL,
    severity          VARCHAR(10)  NOT NULL,
    type              VARCHAR(50)  NOT NULL,
    sku_id            VARCHAR(20)  NOT NULL,
    region            VARCHAR(30)  NOT NULL,
    facts             JSONB,
    action            TEXT,
    is_acknowledged   BOOLEAN      NOT NULL DEFAULT FALSE,
    acknowledged_by   VARCHAR(100),
    acknowledged_at   TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);


-- =============================================================
-- [OUTPUT] 21. alert_digest
-- AI-generated (Gemma/LLM) daily narrative for CSCO.
-- One digest per day.
-- =============================================================
CREATE TABLE alert_digest (
    id               BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date       DATE         NOT NULL,
    review_mode      VARCHAR(30)  NOT NULL,
    surge_regions    TEXT,
    red_alert_count  INT          NOT NULL DEFAULT 0,
    digest_text      TEXT         NOT NULL,
    model_used       VARCHAR(50),
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_digest_date UNIQUE (as_of_date)
);


-- =============================================================
-- [OUTPUT] 22. rolling_run_log
-- Audit trail of every daily pipeline execution.
-- =============================================================
CREATE TABLE rolling_run_log (
    id                    BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date            DATE         NOT NULL,
    previous_as_of_date   DATE,
    models_used           VARCHAR(100),
    lgbm_weight           DECIMAL(5,3),
    chronos_weight        DECIMAL(5,3),
    wmape                 DECIMAL(8,4),
    forecast_rows         INT,
    status                VARCHAR(20)  NOT NULL DEFAULT 'success',
    error_message         TEXT,
    run_duration_seconds  INT,
    triggered_by          VARCHAR(50)  NOT NULL DEFAULT 'cron',
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_run_date UNIQUE (as_of_date)
);


-- =============================================================
-- Indexes
-- =============================================================
CREATE INDEX sku_master_idx_atc_code ON sku_master (atc_code);
CREATE INDEX sku_master_idx_criticality ON sku_master (criticality);
CREATE INDEX locations_idx_type ON locations (type);
CREATE INDEX lanes_idx_to_location ON lanes (to_location);
CREATE INDEX lanes_idx_mode ON lanes (mode);
CREATE INDEX distributors_idx_region ON distributors (region);
CREATE INDEX promo_calendar_idx_promo_id ON promo_calendar (promo_id);
CREATE INDEX promo_calendar_idx_dates ON promo_calendar (start_date, end_date);
CREATE INDEX promo_calendar_idx_status ON promo_calendar (status);
CREATE INDEX demand_history_idx_date ON demand_history (date);
CREATE INDEX demand_history_idx_sku_region ON demand_history (sku_id, region);
CREATE INDEX demand_history_idx_atc_date ON demand_history (atc_code, date);
CREATE INDEX disease_burden_index_idx_region_date ON disease_burden_index (region, record_date);
CREATE INDEX inventory_batches_idx_snapshot ON inventory_batches (as_of_date, location);
CREATE INDEX inventory_batches_idx_sku_loc ON inventory_batches (sku_id, location);
CREATE INDEX inventory_batches_idx_expiry ON inventory_batches (expiry_date);
CREATE INDEX inventory_batches_idx_status ON inventory_batches (status);
CREATE INDEX distributor_orders_idx_distributor ON distributor_orders (distributor_id);
CREATE INDEX distributor_orders_idx_region_date ON distributor_orders (region, order_date);
CREATE INDEX distributor_orders_idx_sku_date ON distributor_orders (sku_id, order_date);
CREATE INDEX distributor_orders_idx_status ON distributor_orders (fulfillment_status);
CREATE INDEX warehouse_capacity_log_idx_location_date ON warehouse_capacity_log (location_id, snapshot_date);
CREATE INDEX warehouse_capacity_log_idx_utilization ON warehouse_capacity_log (utilization_pct);
CREATE INDEX sku_market_share_monthly_idx_atc_period ON sku_market_share_monthly (atc_code, period_year, period_month);
CREATE INDEX location_demand_summary_idx_year_quarter ON location_demand_summary (period_year, period_quarter);
CREATE INDEX sku_cost_history_idx_sku_cost ON sku_cost_history (sku_id, effective_from);
CREATE INDEX sku_cost_history_idx_active ON sku_cost_history (sku_id, effective_to);
CREATE INDEX forecasts_final_idx_as_of ON forecasts_final (as_of_date);
CREATE INDEX forecasts_final_idx_sku_region ON forecasts_final (sku_id, region);
CREATE INDEX forecasts_final_idx_forecast_date ON forecasts_final (forecast_date);
CREATE INDEX replenishment_orders_idx_as_of ON replenishment_orders (as_of_date);
CREATE INDEX replenishment_orders_idx_status ON replenishment_orders (status);
CREATE INDEX replenishment_orders_idx_criticality ON replenishment_orders (criticality);
CREATE INDEX transfer_plan_idx_as_of ON transfer_plan (as_of_date);
CREATE INDEX transfer_plan_idx_sku ON transfer_plan (sku_id);
CREATE INDEX transfer_plan_idx_from_to ON transfer_plan (from_location, to_location);
CREATE INDEX transfer_plan_idx_reason ON transfer_plan (reason);
CREATE INDEX writeoff_risk_idx_as_of ON writeoff_risk (as_of_date);
CREATE INDEX writeoff_risk_idx_sku_loc ON writeoff_risk (sku_id, location);
CREATE INDEX writeoff_risk_idx_expiry ON writeoff_risk (expiry_date);
CREATE INDEX simulation_daily_idx_run ON simulation_daily (as_of_date, policy);
CREATE INDEX simulation_daily_idx_date_region ON simulation_daily (date, region);
CREATE INDEX simulation_daily_idx_sku ON simulation_daily (sku_id);
CREATE INDEX simulation_daily_idx_criticality ON simulation_daily (criticality);
CREATE INDEX kpi_summary_idx_as_of ON kpi_summary (as_of_date);
CREATE INDEX alerts_idx_as_of ON alerts (as_of_date);
CREATE INDEX alerts_idx_severity ON alerts (severity);
CREATE INDEX alerts_idx_type ON alerts (type);
CREATE INDEX alerts_idx_unacknowledged ON alerts (as_of_date, is_acknowledged);
CREATE INDEX rolling_run_log_idx_status ON rolling_run_log (status);

-- =============================================================
-- Trigger function to emulate MySQL "ON UPDATE CURRENT_TIMESTAMP"
-- =============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sku_master_set_updated_at
    BEFORE UPDATE ON sku_master
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_locations_set_updated_at
    BEFORE UPDATE ON locations
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_promo_calendar_set_updated_at
    BEFORE UPDATE ON promo_calendar
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();


-- =============================================================
-- Table and column comments
-- =============================================================
COMMENT ON TABLE sku_master IS 'Product master — one row per SKU';
COMMENT ON TABLE locations IS 'Warehouse and DC master';
COMMENT ON TABLE lanes IS 'Logistics lanes between nodes';
COMMENT ON TABLE distributors IS 'Distributor master per region';
COMMENT ON TABLE promo_calendar IS 'Marketing promo calendar with planned and actual uplifts';
COMMENT ON TABLE demand_history IS 'Daily sales history — primary ML training data';
COMMENT ON TABLE disease_burden_index IS 'Daily disease burden index per region — sourced from public health surveillance';
COMMENT ON TABLE inventory_batches IS 'Daily inventory batch snapshots';
COMMENT ON TABLE distributor_orders IS 'Historical distributor orders — captures real ordering patterns, cycle times and fulfillment rates';
COMMENT ON TABLE warehouse_capacity_log IS 'Weekly warehouse capacity utilization history — shows how storage load evolved over time';
COMMENT ON TABLE sku_market_share_monthly IS 'Monthly brand market share computed from actual sales — organically drifts over time';
COMMENT ON TABLE location_demand_summary IS 'Quarterly regional demand share — computed from demand_history, shows organic demand drift';
COMMENT ON TABLE sku_cost_history IS 'SKU cost timeline — costs change with supplier negotiations and regulatory revisions';
COMMENT ON TABLE forecasts_final IS 'ML ensemble demand forecasts — one batch per daily rollover run';
COMMENT ON TABLE replenishment_orders IS 'Daily replenishment order plan';
COMMENT ON TABLE transfer_plan IS 'Stock transfer recommendations to prevent expiry and resolve shortages';
COMMENT ON TABLE writeoff_risk IS 'Residual expiry write-off risk after transfer plan optimization';
COMMENT ON TABLE simulation_daily IS 'Daily simulation log for policy comparison';
COMMENT ON TABLE kpi_summary IS 'KPI summary per policy per daily run';
COMMENT ON TABLE alerts IS 'Actionable supply chain alerts';
COMMENT ON TABLE alert_digest IS 'Daily AI-generated escalation brief for Chief Supply Chain Officer';
COMMENT ON TABLE rolling_run_log IS 'Audit trail of every daily rollover pipeline run';

COMMENT ON COLUMN sku_master.sku_id IS 'e.g. M01AB-01';
COMMENT ON COLUMN sku_master.brand_name IS 'e.g. Inflamac';
COMMENT ON COLUMN sku_master.atc_code IS 'e.g. M01AB';
COMMENT ON COLUMN sku_master.manufacturer IS 'e.g. Cipla Ltd';
COMMENT ON COLUMN sku_master.regulatory_class IS 'Schedule H | Schedule H1 | OTC';
COMMENT ON COLUMN sku_master.hsn_code IS 'Indian HSN code for GST';
COMMENT ON COLUMN sku_master.nlem_listed IS 'National List of Essential Medicines';
COMMENT ON COLUMN sku_master.criticality IS 'critical | high | standard | low';
COMMENT ON COLUMN sku_master.criticality_rationale IS 'Business reason for this classification';
COMMENT ON COLUMN sku_master.criticality_reviewed_on IS 'Last SOP review date';
COMMENT ON COLUMN sku_master.criticality_reviewed_by IS 'e.g. supply_chain_committee@pharma.in';
COMMENT ON COLUMN sku_master.unit_cost_inr IS 'Current unit cost (see sku_cost_history for full timeline)';
COMMENT ON COLUMN sku_master.shelf_life_days IS 'Approved shelf life in days';
COMMENT ON COLUMN locations.location_id IS 'e.g. DC_MUMBAI';
COMMENT ON COLUMN locations.name IS 'e.g. Mumbai Metro DC';
COMMENT ON COLUMN locations.type IS 'metro_dc | tier2_wh';
COMMENT ON COLUMN locations.city IS 'e.g. Mumbai';
COMMENT ON COLUMN locations.state IS 'e.g. Maharashtra';
COMMENT ON COLUMN locations.gstin IS 'GST registration number';
COMMENT ON COLUMN locations.commissioned_on IS 'When this location went live';
COMMENT ON COLUMN lanes.from_location IS 'SUPPLIER or a location_id';
COMMENT ON COLUMN lanes.to_location IS 'FK → locations.location_id';
COMMENT ON COLUMN lanes.mode IS 'replenish | transfer';
COMMENT ON COLUMN lanes.carrier IS 'e.g. Blue Dart, TCI';
COMMENT ON COLUMN distributors.distributor_id IS 'e.g. DST_DC_MUMBAI';
COMMENT ON COLUMN distributors.region IS 'FK → locations.location_id';
COMMENT ON COLUMN distributors.distributor_name IS 'e.g. Mumbai MedSupply Pvt Ltd';
COMMENT ON COLUMN distributors.order_cycle_days IS 'Average days between orders';
COMMENT ON COLUMN distributors.order_size_sigma IS 'Order sizing noise sigma';
COMMENT ON COLUMN promo_calendar.promo_id IS 'e.g. PRM_WINTER_2018';
COMMENT ON COLUMN promo_calendar.planned_uplift_pct IS 'Expected demand lift e.g. 0.25 = 25%';
COMMENT ON COLUMN promo_calendar.actual_uplift_pct IS 'Measured post-event; NULL if future/active';
COMMENT ON COLUMN promo_calendar.regions IS 'Comma-separated location_ids or ALL';
COMMENT ON COLUMN promo_calendar.target_atc_codes IS 'Comma-separated ATC codes targeted';
COMMENT ON COLUMN promo_calendar.status IS 'planned | active | completed | cancelled';
COMMENT ON COLUMN promo_calendar.created_by IS 'e.g. marketing_team@pharma.in';
COMMENT ON COLUMN demand_history.sku_id IS 'FK → sku_master.sku_id';
COMMENT ON COLUMN demand_history.atc_code IS 'Denormalized for query speed';
COMMENT ON COLUMN demand_history.region IS 'FK → locations.location_id';
COMMENT ON COLUMN disease_burden_index.region IS 'FK → locations.location_id';
COMMENT ON COLUMN disease_burden_index.index_value IS 'ILI burden score';
COMMENT ON COLUMN disease_burden_index.index_type IS 'ili = Influenza-Like Illness';
COMMENT ON COLUMN disease_burden_index.source IS 'Data source e.g. IDSP_State_Surveillance, WHO_GISRS';
COMMENT ON COLUMN disease_burden_index.source_lag_days IS 'Typical days between actual date and data availability';
COMMENT ON COLUMN inventory_batches.as_of_date IS 'Snapshot date';
COMMENT ON COLUMN inventory_batches.batch_id IS 'e.g. B00001';
COMMENT ON COLUMN inventory_batches.sku_id IS 'FK → sku_master.sku_id';
COMMENT ON COLUMN inventory_batches.location IS 'FK → locations.location_id';
COMMENT ON COLUMN inventory_batches.status IS 'healthy | watch | near_expiry_risk | stockout';
COMMENT ON COLUMN inventory_batches.grn_number IS 'Goods Receipt Note reference';
COMMENT ON COLUMN distributor_orders.order_id IS 'Distributor PO reference number';
COMMENT ON COLUMN distributor_orders.distributor_id IS 'FK → distributors.distributor_id';
COMMENT ON COLUMN distributor_orders.region IS 'FK → locations.location_id';
COMMENT ON COLUMN distributor_orders.sku_id IS 'FK → sku_master.sku_id';
COMMENT ON COLUMN distributor_orders.atc_code IS 'Denormalized for query speed';
COMMENT ON COLUMN distributor_orders.order_date IS 'Date PO was raised by distributor';
COMMENT ON COLUMN distributor_orders.expected_delivery IS 'Promised delivery date';
COMMENT ON COLUMN distributor_orders.actual_delivery IS 'Actual delivery date (NULL if pending)';
COMMENT ON COLUMN distributor_orders.ordered_qty IS 'Units ordered';
COMMENT ON COLUMN distributor_orders.fulfilled_qty IS 'Units actually delivered';
COMMENT ON COLUMN distributor_orders.unit_cost_inr IS 'Cost at time of order';
COMMENT ON COLUMN distributor_orders.order_value_inr IS 'ordered_qty × unit_cost_inr';
COMMENT ON COLUMN distributor_orders.days_since_last_order IS 'Actual cycle length — shows ordering pattern';
COMMENT ON COLUMN distributor_orders.fulfillment_status IS 'pending | partial | fulfilled | cancelled';
COMMENT ON COLUMN distributor_orders.shortfall_qty IS 'ordered_qty − fulfilled_qty; 0 if fully served';
COMMENT ON COLUMN warehouse_capacity_log.snapshot_date IS 'Date of this capacity reading (weekly)';
COMMENT ON COLUMN warehouse_capacity_log.location_id IS 'FK → locations.location_id';
COMMENT ON COLUMN warehouse_capacity_log.capacity_units IS 'Max capacity at this location on this date';
COMMENT ON COLUMN warehouse_capacity_log.used_units IS 'Total units on hand (sum of inventory_batches.qty_units)';
COMMENT ON COLUMN warehouse_capacity_log.available_units IS 'capacity_units − used_units';
COMMENT ON COLUMN warehouse_capacity_log.utilization_pct IS 'used / capacity × 100';
COMMENT ON COLUMN warehouse_capacity_log.near_expiry_units IS 'Units expiring within 90 days (risk flag)';
COMMENT ON COLUMN warehouse_capacity_log.sku_count IS 'Number of distinct SKUs stored at this location';
COMMENT ON COLUMN sku_market_share_monthly.sku_id IS 'FK → sku_master.sku_id';
COMMENT ON COLUMN sku_market_share_monthly.period_year IS 'e.g. 2018';
COMMENT ON COLUMN sku_market_share_monthly.period_month IS '1–12';
COMMENT ON COLUMN sku_market_share_monthly.total_units_sold IS 'Units of this SKU in the month';
COMMENT ON COLUMN sku_market_share_monthly.category_units_sold IS 'Total units of the ATC category';
COMMENT ON COLUMN sku_market_share_monthly.market_share IS 'sku_units / category_units';
COMMENT ON COLUMN sku_market_share_monthly.computed_on IS 'When analytics ran this aggregation';
COMMENT ON COLUMN location_demand_summary.location_id IS 'FK → locations.location_id';
COMMENT ON COLUMN location_demand_summary.period_quarter IS '1 | 2 | 3 | 4';
COMMENT ON COLUMN location_demand_summary.total_units IS 'Total units from this location in the quarter';
COMMENT ON COLUMN location_demand_summary.national_share IS 'This location / all locations';
COMMENT ON COLUMN location_demand_summary.yoy_growth_pct IS 'Year-over-year growth % vs same quarter prior year';
COMMENT ON COLUMN sku_cost_history.sku_id IS 'FK → sku_master.sku_id';
COMMENT ON COLUMN sku_cost_history.effective_to IS 'NULL = currently active';
COMMENT ON COLUMN sku_cost_history.reason IS 'e.g. Annual supplier renegotiation, GST transition';
COMMENT ON COLUMN sku_cost_history.approved_by IS 'e.g. procurement@pharma.in';
COMMENT ON COLUMN forecasts_final.as_of_date IS 'Date the forecast was generated';
COMMENT ON COLUMN forecasts_final.atc_code IS 'Denormalized';
COMMENT ON COLUMN forecasts_final.forecast_date IS 'Future date being predicted';
COMMENT ON COLUMN forecasts_final.horizon IS 'Days ahead (1–42)';
COMMENT ON COLUMN forecasts_final.p10 IS '10th percentile forecast';
COMMENT ON COLUMN forecasts_final.p50 IS 'Median forecast';
COMMENT ON COLUMN forecasts_final.p90 IS '90th percentile forecast';
COMMENT ON COLUMN forecasts_final.momentum_u IS 'Recent demand momentum ratio';
COMMENT ON COLUMN forecasts_final.flu_ratio IS 'ILI index ratio vs 14 days prior';
COMMENT ON COLUMN forecasts_final.sense_adjustment IS 'Total sensing uplift applied';
COMMENT ON COLUMN forecasts_final.models_used IS 'e.g. lgbm,chronos';
COMMENT ON COLUMN replenishment_orders.service_level IS 'e.g. 0.99';
COMMENT ON COLUMN replenishment_orders.mu_daily IS 'Mean daily demand from forecast';
COMMENT ON COLUMN replenishment_orders.sigma_daily IS 'Std dev of daily demand';
COMMENT ON COLUMN replenishment_orders.days_of_supply_on_hand IS 'NULL if stockout';
COMMENT ON COLUMN replenishment_orders.status IS 'ok | low | stockout_risk';
COMMENT ON COLUMN transfer_plan.batch_id IS 'Source inventory batch';
COMMENT ON COLUMN transfer_plan.reason IS 'expiry_rescue | shortage_rescue';
COMMENT ON COLUMN transfer_plan.src_days_of_supply_before IS 'Source DOS before this transfer';
COMMENT ON COLUMN writeoff_risk.leftover IS 'Units likely unsold before expiry';
COMMENT ON COLUMN writeoff_risk.residual_writeoff_units IS 'Units that will be written off post-transfers';
COMMENT ON COLUMN writeoff_risk.residual_value_inr IS 'INR financial loss';
COMMENT ON COLUMN simulation_daily.as_of_date IS 'Simulation run date';
COMMENT ON COLUMN simulation_daily.policy IS 'proposed | status_quo';
COMMENT ON COLUMN simulation_daily.date IS 'Simulated calendar date';
COMMENT ON COLUMN kpi_summary.policy IS 'proposed | status_quo';
COMMENT ON COLUMN alerts.severity IS 'RED | AMBER';
COMMENT ON COLUMN alerts.type IS 'shortage_risk | expiry_writeoff_risk | demand_surge_detected';
COMMENT ON COLUMN alerts.sku_id IS '* for region-wide alerts';
COMMENT ON COLUMN alerts.facts IS 'Alert-specific metrics (days_of_supply, units_at_risk, etc.)';
COMMENT ON COLUMN alerts.action IS 'Recommended action text';
COMMENT ON COLUMN alert_digest.review_mode IS 'WEEKLY_STANDARD | DAILY_SURGE_MODE';
COMMENT ON COLUMN alert_digest.surge_regions IS 'Comma-separated regions in demand surge';
COMMENT ON COLUMN alert_digest.digest_text IS 'Full LLM narrative for the CSCO';
COMMENT ON COLUMN alert_digest.model_used IS 'e.g. gemma4:e2b | template_fallback';
COMMENT ON COLUMN rolling_run_log.models_used IS 'e.g. lgbm,chronos';
COMMENT ON COLUMN rolling_run_log.wmape IS 'Realized WMAPE vs actuals (NULL if no actuals yet)';
COMMENT ON COLUMN rolling_run_log.status IS 'success | partial | failed';
COMMENT ON COLUMN rolling_run_log.triggered_by IS 'cron | manual | api';


-- =============================================================
-- [OUTPUT] 23. model_evaluation_metrics
-- Model performance metrics computed after each pipeline run.
-- =============================================================
CREATE TABLE model_evaluation_metrics (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    as_of_date      DATE         NOT NULL,
    model_name      VARCHAR(30)  NOT NULL,
    metric_name     VARCHAR(30)  NOT NULL,
    metric_value    DECIMAL(10,6),
    horizon_band    VARCHAR(20),
    computed_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_metric UNIQUE (as_of_date, model_name, metric_name, horizon_band)
);

COMMENT ON TABLE model_evaluation_metrics IS 'Model performance metrics — WMAPE, MAE, RMSE, MAPE, R² per model per horizon band';
COMMENT ON COLUMN model_evaluation_metrics.model_name IS 'ensemble | lgbm | chronos | nhits | tft';
COMMENT ON COLUMN model_evaluation_metrics.metric_name IS 'wmape | mae | rmse | mape | r2';
COMMENT ON COLUMN model_evaluation_metrics.horizon_band IS '1-7 | 8-14 | 15-21 | 22-42 | NULL (overall)';

CREATE INDEX model_evaluation_metrics_idx_as_of ON model_evaluation_metrics (as_of_date);
CREATE INDEX model_evaluation_metrics_idx_model ON model_evaluation_metrics (model_name);


-- =============================================================
-- [STATE] 24. pipeline_state
-- Single-row table holding the simulated "today" date.
-- The backend advances this; ML pipelines read it.
-- =============================================================
CREATE TABLE pipeline_state (
    id              INT PRIMARY KEY DEFAULT 1,
    simulated_today DATE NOT NULL DEFAULT '2019-01-17',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT single_row CHECK (id = 1)
);

COMMENT ON TABLE pipeline_state IS 'Simulated today date — single row, advanced by the backend, read by ML pipelines';


-- =============================================================
-- [STATE] 24. pipeline_state
-- Single-row table holding the simulated "today" date.
-- All pipelines read from here instead of MAX(date) or config.yaml.
-- The backend advances this date; the ML project only reads it.
-- =============================================================
CREATE TABLE pipeline_state (
    id              INT PRIMARY KEY DEFAULT 1,
    simulated_today DATE NOT NULL DEFAULT '2019-01-17',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT single_row CHECK (id = 1)
);

COMMENT ON TABLE pipeline_state IS 'Simulated today date — single row, advanced by the backend, read by ML pipelines';


-- =============================================================
-- [STAGING] 25-29. Pre-loaded future data for demo simulation.
-- Backend advances pipeline_state.simulated_today, then ML
-- promote_staging.py moves that day's rows from staging → live.
-- =============================================================

CREATE TABLE demand_history_staging (
    date        DATE NOT NULL,
    sku_id      VARCHAR(20) NOT NULL,
    atc_code    VARCHAR(10) NOT NULL,
    region      VARCHAR(30) NOT NULL,
    units       INT NOT NULL DEFAULT 0,
    PRIMARY KEY (date, sku_id, region)
);
COMMENT ON TABLE demand_history_staging IS 'Future demand data — promoted to demand_history one day at a time';

CREATE TABLE disease_burden_staging (
    record_date DATE NOT NULL,
    region      VARCHAR(30) NOT NULL,
    index_value DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (record_date, region)
);
COMMENT ON TABLE disease_burden_staging IS 'Future flu/ILI data — promoted to disease_burden_index one day at a time';

CREATE TABLE inventory_staging (
    as_of_date    DATE NOT NULL,
    batch_id      VARCHAR(20) NOT NULL,
    sku_id        VARCHAR(20) NOT NULL,
    location      VARCHAR(30) NOT NULL,
    qty_units     INT NOT NULL DEFAULT 0,
    expiry_date   DATE NOT NULL,
    received_date DATE NOT NULL,
    unit_cost_inr INT NOT NULL,
    status        VARCHAR(30) NOT NULL,
    PRIMARY KEY (as_of_date, batch_id)
);
COMMENT ON TABLE inventory_staging IS 'Future inventory snapshots — promoted to inventory_batches one snapshot at a time';

CREATE TABLE distributor_orders_staging (
    order_id              VARCHAR(40) NOT NULL,
    distributor_id        VARCHAR(30) NOT NULL,
    region                VARCHAR(30) NOT NULL,
    sku_id                VARCHAR(20) NOT NULL,
    atc_code              VARCHAR(10) NOT NULL,
    order_date            DATE NOT NULL,
    expected_delivery     DATE,
    actual_delivery       DATE,
    ordered_qty           INT NOT NULL,
    fulfilled_qty         INT NOT NULL DEFAULT 0,
    unit_cost_inr         INT NOT NULL,
    order_value_inr       INT NOT NULL,
    days_since_last_order INT,
    fulfillment_status    VARCHAR(20) NOT NULL DEFAULT 'pending',
    shortfall_qty         INT NOT NULL DEFAULT 0,
    PRIMARY KEY (order_date, order_id, sku_id)
);
COMMENT ON TABLE distributor_orders_staging IS 'Future distributor orders — promoted to distributor_orders by order_date';

CREATE TABLE warehouse_capacity_staging (
    snapshot_date    DATE NOT NULL,
    location_id      VARCHAR(30) NOT NULL,
    capacity_units   INT NOT NULL,
    used_units       INT NOT NULL,
    available_units  INT NOT NULL,
    utilization_pct  DECIMAL(5,2) NOT NULL,
    near_expiry_units INT NOT NULL DEFAULT 0,
    sku_count        INT NOT NULL DEFAULT 0,
    PRIMARY KEY (snapshot_date, location_id)
);
COMMENT ON TABLE warehouse_capacity_staging IS 'Future capacity snapshots — promoted to warehouse_capacity_log by snapshot_date';


-- =============================================================
-- [AUTH] 30. users
-- Application accounts for email + password authentication.
-- Passwords are stored ONLY as bcrypt hashes — never plaintext.
-- =============================================================
CREATE TABLE IF NOT EXISTS users (
    id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(320) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'viewer',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

COMMENT ON TABLE users IS 'Application accounts for email + password authentication';
COMMENT ON COLUMN users.role IS 'admin | viewer | analyst';

CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();


